mailConfig:
  #protocol: smtp
  host: 192.168.22.14
  port: 25
  auth: false
  user: nobody
  password: 

mailNotification:
  general:
    subject: No-reply - NOTIFICATION from Activity
    sender: noreply.test.vn.01@gmail.com
    recipients:
      #- quoc383011@gmail.com
      - ducquoc.vn@gmail.com
